### ISSUE TITLE
Pause Stream to take photo

### ISSUE THREAD

**Issue by cjjaeckson** [kwasmich/PICS#1]
Hi,
thanks for your project, it works fine and is easy to use.
One question:
I use PICs to run a webcam stream for a 3D-printing monitoring. Additionally I have a TelegramBot installed that takes a photo and sends it to a chat. Unfortunately both at the same time does not work, because the video0 is busy by PICS. 
I've tried to solve this problem by "killall" the PICS process, run fswebcam to take the foto, run PICS again and send it to the Telegram chat with a bash script. Now it came to the next problem: Your PICS process doesn't stop running, because its waiting for clients. So in the bash script it never comes to a sending of the picture to Telegram.
So my question is: Can I pause your process or destroy and start it again in the bash script? Or can I run it in background?
Hope you can help me.
Thanks!
Chris

**Comment by cjjaeckson** [comment]
I solved it by using '>/dev/null 2>&1 &' at the end. Thanks.

**Comment by kwasmich** [comment]
An alternative solution would be to not stop PICS at all. You can always get a still picture by accessing `/dev/still0` instead of `/dev/video0`. So your telegram bot could download the still image and send it to you.

**Comment by kwasmich** [comment]
`curl` to rescue!
`curl -o /home/pi/microserver/tw/CAM1.jpg http://localhost:8080/dev/still0`
